# Generated by Django 3.1.6 on 2021-02-15 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catsapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat',
            name='color',
        ),
        migrations.AlterField(
            model_name='cat',
            name='breed',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Breed',
        ),
        migrations.DeleteModel(
            name='Color',
        ),
    ]
