# Generated by Django 3.1.6 on 2021-02-15 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catsapi', '0003_auto_20210215_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='birth',
            field=models.DateField(blank=True),
        ),
    ]
