# Generated by Django 3.1.6 on 2021-02-15 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catsapi', '0004_auto_20210215_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
