# Generated by Django 3.1.6 on 2021-02-16 05:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('catsapi', '0005_auto_20210215_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 2, 16, 5, 50, 20, 117078, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
