# Generated by Django 3.1.6 on 2021-02-16 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catsapi', '0006_cat_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='photo',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
