# Generated by Django 3.1.6 on 2021-02-16 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catsapi', '0007_auto_20210216_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='photo',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
