# Generated by Django 3.1.6 on 2021-02-16 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catsapi', '0008_auto_20210216_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='photo',
            field=models.ImageField(default='', null=True, upload_to=''),
        ),
    ]
